rootProject.name = "my-vee-port"
include("vee-port", "vee-port:front-panel", "vee-port:mock", "vee-port:image-generator", "app")

project(":vee-port:front-panel").projectDir = file("vee-port/extensions/front-panel")
project(":vee-port:mock").projectDir = file("vee-port/mock")
project(":vee-port:image-generator").projectDir = file("vee-port/extensions/image-generator")

include("vee-port:validation:java-testsuite-runner-audio")
include("vee-port:validation:java-testsuite-runner-core")
include("vee-port:validation:java-testsuite-runner-ecom-wifi")
include("vee-port:validation:java-testsuite-runner-event-queue")
include("vee-port:validation:java-testsuite-runner-ext-res-loader")
include("vee-port:validation:java-testsuite-runner-fs")
include("vee-port:validation:java-testsuite-runner-gnss")
include("vee-port:validation:java-testsuite-runner-gpio")
include("vee-port:validation:java-testsuite-runner-net")
include("vee-port:validation:java-testsuite-runner-security")
include("vee-port:validation:java-testsuite-runner-ssl")
include("vee-port:validation:java-testsuite-runner-ui3")
include("vee-port:validation:java-testsuite-runner-vg")
include("vee-port:validation:java-testsuite-runner-watchdog-timer")
project(":vee-port:validation:java-testsuite-runner-audio").projectDir = file("vee-port/validation/audio/java-testsuite-runner-audio")
project(":vee-port:validation:java-testsuite-runner-core").projectDir = file("vee-port/validation/core/java-testsuite-runner-core")
project(":vee-port:validation:java-testsuite-runner-ecom-wifi").projectDir = file("vee-port/validation/ecom-wifi/java-testsuite-runner-ecom-wifi")
project(":vee-port:validation:java-testsuite-runner-event-queue").projectDir = file("vee-port/validation/event-queue/java-testsuite-runner-event-queue")
project(":vee-port:validation:java-testsuite-runner-ext-res-loader").projectDir = file("vee-port/validation/ext-res-loader/java-testsuite-runner-ext-res-loader")
project(":vee-port:validation:java-testsuite-runner-fs").projectDir = file("vee-port/validation/fs/java-testsuite-runner-fs")
project(":vee-port:validation:java-testsuite-runner-gnss").projectDir = file("vee-port/validation/gnss/java-testsuite-runner-gnss")
project(":vee-port:validation:java-testsuite-runner-net").projectDir = file("vee-port/validation/net/java-testsuite-runner-net")
project(":vee-port:validation:java-testsuite-runner-security").projectDir = file("vee-port/validation/security/java-testsuite-runner-security")
project(":vee-port:validation:java-testsuite-runner-ssl").projectDir = file("vee-port/validation/ssl/java-testsuite-runner-ssl")
project(":vee-port:validation:java-testsuite-runner-ui3").projectDir = file("vee-port/validation/ui/java-testsuite-runner-ui3")
project(":vee-port:validation:java-testsuite-runner-vg").projectDir = file("vee-port/validation/vg/java-testsuite-runner-vg")
project(":vee-port:validation:java-testsuite-runner-watchdog-timer").projectDir = file("vee-port/validation/watchdog-timer/java-testsuite-runner-watchdog-timer")